### ISSUE TITLE
How to solve this error??

### ISSUE THREAD

**Issue by Daehyun-Bae** [alicehzheng/teamform-seed#88]
After login, go to userprofile page there is an erreor message
_TypeError: cannot read property 'join' of undefined_
Where this error is coming?? Can I ignore that?
Im trying to implement tagsinput.js and find while testing

**Comment by lguillain** [comment]
Ignore it for now, it's an error in the database structure. I will fix it for you now. tell me it it worked out 
-> I'll need to update the log in in a bit. give me until tonight

**Comment by lguillain** [comment]
Hi I fixed the issue. just merge the pull request and everything should work perfectly

**Comment by Daehyun-Bae** [comment]
Thx
